Repository superdesk/web-publisher, pull requests merged in 2019-08, with the labels that each got.

#931 remove package guid contraint unles solution for legacy updates will …
  src/SWP/Bundle/CoreBundle/Migrations/2019/07/Version20190710074938.php
Labels: bug

#932 add more upgrade notes
  CHANGELOG.md
  UPGRADE.md
  docs/cookbooks/implementators/index.rst
  docs/cookbooks/implementators/setup_oauth_login_with_auth0.rst
  docs/reference/system_requirements.rst
  src/SWP/Bundle/ContentBundle/composer.json
Labels: documentation

#936 [Fix] theme translations and config loading
  src/SWP/Bundle/CoreBundle/EventListener/TenantNotFoundExceptionListener.php
  src/SWP/Bundle/CoreBundle/Fragment/ExternalFragmentRenderer.php
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/Theme/Configuration/TenantableConfigurationSourceFactory.php
  src/SWP/Bundle/CoreBundle/Theme/Locator/TenantThemesConfigurationFileLocator.php
  src/SWP/Bundle/CoreBundle/Theme/Provider/TenantThemesPathsProvider.php
  src/SWP/Bundle/CoreBundle/Theme/Provider/TenantThemesPathsProviderInterface.php
Labels: Improvement

#937 fix articles catching for automated content lists
  features/content_lists/add_article_to_multiple_automatic_content_lists.feature
  src/SWP/Behat/Contexts/ContentListContext.php
  src/SWP/Behat/Contexts/RouteContext.php
  src/SWP/Bundle/ContentBundle/Rule/Applicator/ArticleRuleApplicator.php
  src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php
  src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php
  src/SWP/Bundle/CoreBundle/Matcher/ArticleCriteriaMatcher.php
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/Rule/Populator/ArticlePopulator.php
  src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php
Labels: bug

#940 handle url's with trailing slashes properly
  config/routes.yaml
  src/SWP/Bundle/ContentBundle/DependencyInjection/Compiler/OverrideCmfFinalMatcherPass.php
  src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php
  src/SWP/Bundle/ContentBundle/Routing/FinalMatcher.php
  src/SWP/Bundle/ContentBundle/SWPContentBundle.php
  src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php
  src/SWP/Bundle/CoreBundle/Tests/Controller/RedirectingControllerTest.php
Labels: bug

#943 SWP-1730 - Themes are not loaded in the website settings
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
Labels: bug
