Repository superdesk/web-publisher, pull requests merged in 2019-12, with the labels that each got.

#1010 Improve metadata matching in content lists filters
  composer.json
  composer.lock
  config/packages/security.yaml
  features/content_lists/add_article_to_list_based_on_unordered_subjects.feature
  features/content_lists/add_article_to_multiple_automatic_content_lists.feature
  features/content_push/check_article_body_via_webhook.feature
  features/content_push/send_content_with_galleries_in_associations.feature
  src/SWP/Bundle/ContentBundle/EventListener/LinkRequestListener.php
  src/SWP/Bundle/ContentBundle/Model/Article.php
  src/SWP/Bundle/ContentBundle/Resources/config/app/config.yml
  src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Article.orm.yml
  src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/Security/Authenticator/ExternalOauthAuthenticator.php
  src/SWP/Bundle/CoreBundle/Security/Authenticator/PreviewTokenAuthenticator.php
  src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php
  src/SWP/Bundle/CoreBundle/Tests/AmpHtmlTest.php
  src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php
  src/SWP/Bundle/CoreBundle/Tests/EventListener/HttpCacheHeaderListenerTest.php
  src/SWP/Bundle/CoreBundle/Tests/Functional/ExternalOauthTest.php
  src/SWP/Bundle/CoreBundle/Tests/Functional/Resources/package-lock.json
  src/SWP/Component/Common/ArrayHelper.php
  src/SWP/Component/Common/Request/RequestParser.php
  src/SWP/Component/ContentList/Model/ContentList.php
  symfony.lock
Labels: Improvement

#1013 [fix] safely save loader parameters
  src/SWP/Bundle/TemplatesSystemBundle/Loader/TraceableChainLoader.php
Labels: bugfix

#1009 Restrict access to articles based on geo-location
  .env
  .env.test
  behat.yml.dist
  composer.json
  composer.lock
  config/bundles.php
  config/packages/test/behat.yaml
  docs/bundles/SWPGeoIPBundle/configuration.rst
  docs/bundles/SWPGeoIPBundle/index.rst
  docs/bundles/SWPGeoIPBundle/installation.rst
  docs/cookbooks/developers/geoip.rst
  docs/cookbooks/developers/index.rst
  docs/cookbooks/developers/websocket.rst
  features/bootstrap/GeoLocationContext.php
  features/geolocation/restrict_access_to_articles_based_on_location.feature
  src/SWP/Behat/Service/GeoIPReaderAdapterStub.php
  src/SWP/Bundle/ContentBundle/Model/Article.php
  src/SWP/Bundle/CoreBundle/DependencyInjection/SWPCoreExtension.php
  src/SWP/Bundle/CoreBundle/EventSubscriber/GeoIPSubscriber.php
  src/SWP/Bundle/CoreBundle/GeoIp/CachedGeoIpChecker.php
  src/SWP/Bundle/CoreBundle/Model/Article.php
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/Resources/config/subscribers.yaml
  src/SWP/Bundle/GeoIPBundle/.gitignore
  src/SWP/Bundle/GeoIPBundle/.travis.yml
  src/SWP/Bundle/GeoIPBundle/AUTHORS.md
  src/SWP/Bundle/GeoIPBundle/Command/UpdateGeoIPDatabaseCommand.php
  src/SWP/Bundle/GeoIPBundle/DependencyInjection/Configuration.php
  src/SWP/Bundle/GeoIPBundle/DependencyInjection/SWPGeoIPExtension.php
  src/SWP/Bundle/GeoIPBundle/LICENSE.md
  src/SWP/Bundle/GeoIPBundle/README.md
  src/SWP/Bundle/GeoIPBundle/Resources/config/services.yaml
  src/SWP/Bundle/GeoIPBundle/SWPGeoIPBundle.php
  src/SWP/Bundle/GeoIPBundle/composer.json
  src/SWP/Component/Archiver/.gitignore
  src/SWP/Component/Archiver/.travis.yml
  src/SWP/Component/Archiver/AUTHORS.md
  src/SWP/Component/Archiver/Archiver/ArchiverInterface.php
  src/SWP/Component/Archiver/Archiver/GzipArchiver.php
  src/SWP/Component/Archiver/Archiver/ZipArchiver.php
  src/SWP/Component/Archiver/LICENSE.md
  src/SWP/Component/Archiver/README.md
  src/SWP/Component/Archiver/composer.json
  src/SWP/Component/Archiver/phpspec.yml.dist
  src/SWP/Component/GeoIP/.gitignore
  src/SWP/Component/GeoIP/.travis.yml
  src/SWP/Component/GeoIP/AUTHORS.md
  src/SWP/Component/GeoIP/Checker/GeoIPChecker.php
  src/SWP/Component/GeoIP/LICENSE.md
  src/SWP/Component/GeoIP/Model/GeoIpPlaceInterface.php
  src/SWP/Component/GeoIP/Model/Place.php
  src/SWP/Component/GeoIP/README.md
  src/SWP/Component/GeoIP/Reader/GeoIPReaderAdapter.php
  src/SWP/Component/GeoIP/Reader/ReaderInterface.php
  src/SWP/Component/GeoIP/composer.json
  src/SWP/Component/GeoIP/phpspec.yml.dist
  symfony.lock
Labels: feature

#1017 Redirect routes
  composer.json
  config/bundles.php
  features/redirect_routes/redirect_from_one_route_to_another.feature
  features/redirect_routes/redirect_routes_management.feature
  features/redirect_routes/redirect_to_external_urls.feature
  src/SWP/Bundle/AnalyticsBundle/Model/ArticleStatistics.php
  src/SWP/Bundle/ContentBundle/DependencyInjection/SWPContentExtension.php
  src/SWP/Bundle/ContentBundle/EventListener/DoctrineMetadataListener.php
  src/SWP/Bundle/ContentBundle/EventListener/HttpCacheHeaderListener.php
  src/SWP/Bundle/ContentBundle/Form/Extension/RedirectRouteTypeExtension.php
  src/SWP/Bundle/ContentBundle/Model/RedirectRoute.php
  src/SWP/Bundle/ContentBundle/Model/RedirectRouteInterface.php
  src/SWP/Bundle/ContentBundle/Provider/ORM/RouteProvider.php
  src/SWP/Bundle/ContentBundle/Resources/config/app/config.yml
  src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/RedirectRoute.orm.yml
  src/SWP/Bundle/ContentBundle/Resources/config/listeners.yaml
  src/SWP/Bundle/ContentBundle/Resources/config/providers.orm.yml
  src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.RedirectRoute.yml
  src/SWP/Bundle/ContentBundle/Resources/config/services.yml
  src/SWP/Bundle/ContentBundle/Resources/config/validation.yml
  src/SWP/Bundle/ContentBundle/Tests/Functional/app/AppKernel.php
  src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/bundles.php
  src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/config.yml
  src/SWP/Bundle/ContentBundle/Tests/Provider/RouteProviderTest.php
  src/SWP/Bundle/ContentBundle/composer.json
  src/SWP/Bundle/CoreBundle/Controller/RedirectRouteController.php
  src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php
  src/SWP/Bundle/CoreBundle/EventListener/HttpCacheTaggerListener.php
  src/SWP/Bundle/CoreBundle/Migrations/2019/12/Version20191216090544.php
  src/SWP/Bundle/CoreBundle/Model/RedirectRoute.php
  src/SWP/Bundle/CoreBundle/Model/RedirectRouteInterface.php
  src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
  src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/RedirectRoute.orm.yml
  src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Route.orm.yml
  src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.RedirectRoute.yml
  src/SWP/Bundle/RedirectRouteBundle/.gitignore
  src/SWP/Bundle/RedirectRouteBundle/.travis.yml
  src/SWP/Bundle/RedirectRouteBundle/AUTHORS.md
  src/SWP/Bundle/RedirectRouteBundle/DependencyInjection/Configuration.php
  src/SWP/Bundle/RedirectRouteBundle/DependencyInjection/SWPRedirectRouteExtension.php
  src/SWP/Bundle/RedirectRouteBundle/Form/RedirectRouteType.php
  src/SWP/Bundle/RedirectRouteBundle/LICENSE.md
  src/SWP/Bundle/RedirectRouteBundle/Model/RedirectRoute.php
  src/SWP/Bundle/RedirectRouteBundle/Model/RedirectRouteInterface.php
  src/SWP/Bundle/RedirectRouteBundle/README.md
  src/SWP/Bundle/RedirectRouteBundle/Resources/config/app/config.yml
  src/SWP/Bundle/RedirectRouteBundle/Resources/config/doctrine-orm/RedirectRoute.orm.yml
  src/SWP/Bundle/RedirectRouteBundle/Resources/config/serializer/Model.RedirectRoute.yml
  src/SWP/Bundle/RedirectRouteBundle/Resources/config/services.yaml
  src/SWP/Bundle/RedirectRouteBundle/SWPRedirectRouteBundle.php
  src/SWP/Bundle/RedirectRouteBundle/composer.json
  src/SWP/Component/Common/Model/TimestampableTrait.php
Labels: feature
