Repository superdesk/web-publisher, pull requests merged in 2019-11, with the labels that each got.

#995 Fix content list filling when criteria have complex subject or place
  src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
Labels: bugfix

#996 [SWP-1814] handle new superdesk ways for unpublishing content
  features/02_articles/unpublish_from_superdesk.feature
  src/SWP/Bundle/ContentBundle/EventListener/ArticlePublishListener.php
  src/SWP/Bundle/CoreBundle/EventListener/CanceledPackageListener.php
  src/SWP/Bundle/CoreBundle/EventListener/UpdatedPackageListener.php
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Component/Bridge/Validator/NinjsValidator.php
Labels: feature

#997 [SWP-1812] handle duplicated authors in package
  features/packages/creating_package_with_authors.feature
  src/SWP/Bundle/ContentBundle/EventListener/UpdatePackageAuthorsListener.php
Labels: bugfix

#999 Allow to fetch content lists items also on single package get request
  composer.json
  composer.lock
  src/SWP/Bundle/CoreBundle/Serializer/ContentListAwareSerializationSubscriber.php
Labels: Improvement

#1001 Add public url to rendition
  features/02_articles/set_width_and_height_of_embedded_image.feature
  features/content_push/send_content_with_galleries_in_associations.feature
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/Serializer/ImageRenditionSerializationSubscriber.php
  src/SWP/Bundle/MultiTenancyBundle/Tests/DependencyInjection/Compiler/ConfigurePrefixCandidatesCompilerPassTest.php
Labels: Improvement

#1006 Filter articles by keywords
  docs/manual/templates_system/search.rst
  features/02_articles/searching_articles_by_keywords.feature
  src/SWP/Bundle/ElasticSearchBundle/Controller/Api/ArticleSearchController.php
  src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php
Labels: feature

#1005 fix article publishing when tenant rule contains autopublishing and paywall settings
  composer.lock
  features/paywall/marking_article_as_paywall_secured_by_rule.feature
  src/SWP/Bundle/ContentBundle/Rule/Applicator/ArticleRuleApplicator.php
  src/SWP/Bundle/CoreBundle/Rule/Applicator/PackageRuleApplicator.php
  src/SWP/Bundle/CoreBundle/Rule/Applicator/PaywallSecuredRuleApplicator.php
  src/SWP/Bundle/CoreBundle/Rule/Applicator/PublishArticleToFBIARuleApplicator.php
  src/SWP/Bundle/MultiTenancyBundle/Tests/DependencyInjection/Compiler/ConfigurePrefixCandidatesCompilerPassTest.php
Labels: bugfix

#1004 fix package serializer configuration typo, update dependencies
  composer.lock
  features/packages/get_packages.feature
  src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Package.yml
  src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
  symfony.lock
Labels: bugfix
