Repository superdesk/web-publisher, pull requests merged in 2020-01, with the labels that each got.

#1021 update content list when new item is added to it
  features/bootstrap/FeatureContext.php
  features/bootstrap/JsonContext.php
  features/targeted_publishing/content_lists/creating_targeted_publishing_destinations_with_content_lists.feature
  src/SWP/Bundle/ContentListBundle/Services/ContentListService.php
  src/SWP/Component/ContentList/Model/ContentListItem.php
Labels: bugfix

#1022 Improve twig cache key generation
  src/SWP/Bundle/ContentBundle/Resolver/AssetLocationResolver.php
  src/SWP/Bundle/CoreBundle/Twig/Cache/KeyGenerator/TenantAwareMetaKeyGenerator.php
  src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/LifetimeCacheStrategy.php
  src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/TagAwareIndexedChainingCacheStrategy.php
  src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
  src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/dev/article.yml
  symfony.lock
Labels: bugfix

#1026 fix asset location resolver logic
  src/SWP/Bundle/ContentBundle/Resolver/AssetLocationResolver.php
  src/SWP/Bundle/ContentBundle/spec/Resolver/AssetLocationResolverSpec.php
Labels: bugfix

#1023 add tests for article unpublishing and removing items from content list
  features/content_lists/add_article_to_multiple_automatic_content_lists.feature
  src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php
  src/SWP/Component/Common/Model/SoftDeletableInterface.php
  src/SWP/Component/Common/Model/SoftDeletableTrait.php
Labels: Improvement

#1024 add article to matching content list after correction
  features/content_lists/add_article_to_automatic_list_after_update.feature
  src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php
  src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/spec/EventListener/AddArticleToListListenerSpec.php
Labels: Improvement

#1025 Analytics export
  .env
  bin/console
  composer.json
  composer.lock
  config/packages/mailer.yaml
  config/packages/messenger.yaml
  config/packages/test/messenger.yaml
  etc/scripts/supervisor/supervisor_analytics_export.conf
  features/analytics/export_article_analytics.feature
  src/SWP/Bundle/CoreBundle/AnalyticsExport/CsvFileWriter.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/CsvReportFileLocationResolver.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/Exception/AnalyticsReportNotFoundException.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalytics.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalyticsHandler.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/ReportFileUploader.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/ReportMailer.php
  src/SWP/Bundle/CoreBundle/Controller/AnalyticsExportController.php
  src/SWP/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/SWP/Bundle/CoreBundle/Migrations/2020/01/Version20200107115725.php
  src/SWP/Bundle/CoreBundle/Model/AnalyticsReport.php
  src/SWP/Bundle/CoreBundle/Model/AnalyticsReportInterface.php
  src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
  src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/AnalyticsReport.orm.yml
  src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.AnalyticsReport.yml
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/UserBundle/Model/User.php
  symfony.lock
Labels: feature

#1030 fix content push performance with many galery items
  composer.lock
  src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleMediaListener.php
  src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Image.orm.yml
  src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/config.yml
  src/SWP/Bundle/CoreBundle/Migrations/2020/01/Version20200109113028.php
  symfony.lock
Labels: Improvement

#1033 exclude articles by routes
  features/twig/loaders/exclude_articles_by_routes.feature
  src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
  src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php
Labels: feature

#1039 handle items with slugline property set to empty string
  features/02_articles/validating_article_slugline.feature
  features/content_lists/add_article_to_automatic_list_after_update.feature
  src/SWP/Bundle/BridgeBundle/EventListener/ValidationListener.php
  src/SWP/Bundle/ContentBundle/Model/Article.php
  src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
Labels: enhancement

#1038 search articles by exact author name
  features/02_articles/searching_articles_by_authors.feature
  src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php
  src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml
Labels: enhancement
