Repository superdesk/web-publisher, pull requests merged in 2020-02, with the labels that each got.

#1037 export analytics data by authors, routes, search phrase/title
  behat.yml.dist
  config/packages/test/behat.yaml
  config/packages/test/mailer.yaml
  config/packages/test/messenger.yaml
  features/analytics/export_article_analytics.feature
  src/SWP/Behat/Contexts/AbstractContext.php
  src/SWP/Behat/Contexts/ArticleContext.php
  src/SWP/Behat/Contexts/CsvFileContext.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalytics.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalyticsHandler.php
  src/SWP/Bundle/CoreBundle/AnalyticsExport/ReportFileUploader.php
  src/SWP/Bundle/CoreBundle/Controller/AnalyticsExportController.php
  src/SWP/Bundle/CoreBundle/Model/AnalyticsReport.php
  src/SWP/Bundle/CoreBundle/Model/AnalyticsReportInterface.php
  src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/AnalyticsReport.orm.yml
  src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.AnalyticsReport.yml
Labels: feature

#1043 fix reseting manual content list items whhen list limit changed
  features/content_lists/change_limit_of_content_lists.feature
  src/SWP/Bundle/CoreBundle/EventListener/UpdateContentListItemsListener.php
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
Labels: bugfix

#1045 Merge 2.0 to master
  composer.lock
  features/content_lists/change_limit_of_content_lists.feature
  features/twig/cache_key_generation.feature
  features/twig/cache_tags_collector.feature
  src/SWP/Bundle/CoreBundle/EventListener/BodyListener.php
  src/SWP/Bundle/CoreBundle/EventListener/UpdateContentListItemsListener.php
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/TagAwareIndexedChainingCacheStrategy.php
Labels: version merge

#1046 add article authors to packages, articles and content list items responses
  src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Author.yml
  src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Article.yml
  src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php
  src/SWP/Bundle/ElasticSearchBundle/Controller/Api/ArticleSearchController.php
  src/SWP/Bundle/ElasticSearchBundle/Controller/Api/PackageSearchController.php
Labels: Improvement

#1041 Rewrite Consumers
  .env
  UPGRADE.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/_publisher.yaml
  config/packages/dev/monolog.yaml
  config/packages/dev/old_sound_rabbit_mq.yaml
  config/packages/messenger.yaml
  config/packages/prod/monolog.yaml
  config/packages/test/behat.yaml
  config/packages/test/messenger.yaml
  config/packages/test/old_sound_rabbit_mq.yaml
  etc/scripts/supervisor/publisher-migration-worker.conf
  etc/scripts/supervisor/publisher-worker.conf
  etc/scripts/supervisor/supervisor-websocket.conf
  etc/scripts/supervisor/supervisor_analytics_export.conf
  etc/scripts/supervisor/supervisor_content_push.conf
  etc/scripts/supervisor/supervisor_images_conversion.conf
  etc/scripts/supervisor/supervisor_webhooks.conf
  etc/scripts/supervisor/supervisor_websocket.conf
  src/SWP/Behat/Contexts/PackageContext.php
  src/SWP/Bundle/AnalyticsBundle/EventListener/AnalyticsEventListener.php
  src/SWP/Bundle/AnalyticsBundle/Messenger/AnalyticsEvent.php
  src/SWP/Bundle/AnalyticsBundle/Resources/config/app/config.yml
  src/SWP/Bundle/AnalyticsBundle/Resources/config/services.yml
  src/SWP/Bundle/AnalyticsBundle/composer.json
  src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php
  src/SWP/Bundle/CoreBundle/Command/ProcessPackagesCommand.php
  src/SWP/Bundle/CoreBundle/Consumer/SendWebhookConsumer.php
  src/SWP/Bundle/CoreBundle/DependencyInjection/SWPCoreExtension.php
  src/SWP/Bundle/CoreBundle/EventListener/ImageToWebpConversionListener.php
  src/SWP/Bundle/CoreBundle/EventSubscriber/WebhookEventsSubscriber.php
  src/SWP/Bundle/CoreBundle/Exception/PackageNotFoundException.php
  src/SWP/Bundle/CoreBundle/MessageHandler/AbstractContentPushHandler.php
  src/SWP/Bundle/CoreBundle/MessageHandler/AnalyticsEventHandler.php
  src/SWP/Bundle/CoreBundle/MessageHandler/ContentPushHandler.php
  src/SWP/Bundle/CoreBundle/MessageHandler/ContentPushMigrationHandler.php
  src/SWP/Bundle/CoreBundle/MessageHandler/ImageConversionHandler.php
  src/SWP/Bundle/CoreBundle/MessageHandler/Message/ContentPushMessage.php
  src/SWP/Bundle/CoreBundle/MessageHandler/Message/ContentPushMigrationMessage.php
  src/SWP/Bundle/CoreBundle/MessageHandler/Message/ConvertImageMessage.php
  src/SWP/Bundle/CoreBundle/MessageHandler/WebhookHandler.php
  src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
  src/SWP/Bundle/CoreBundle/Resources/config/commands.yml
  src/SWP/Bundle/CoreBundle/Resources/config/message_handlers.yaml
  src/SWP/Bundle/CoreBundle/Resources/config/services.yml
  src/SWP/Bundle/CoreBundle/Tests/Producer/TestProducer.php
  src/SWP/Bundle/CoreBundle/Webhook/Message/WebhookMessage.php
  src/SWP/Bundle/CoreBundle/spec/Consumer/AnalyticsEventConsumerSpec.php
  supervisor.md
  symfony.lock
Labels: enhancement, feature

#1050 improve articles excluding bu authors
  features/twig/loaders/exclude_articles_by_authors.feature
  src/SWP/Behat/Contexts/ArticleContext.php
  src/SWP/Behat/Contexts/TemplatingContext.php
  src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.BaseContent.yml
  src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
  src/SWP/Bundle/ContentBundle/Model/ArticleAuthorReference.php
  src/SWP/Bundle/ContentBundle/Provider/ORM/ArticleProvider.php
  src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleAuthorReference.orm.yml
Labels: Improvement

#1058 Default organization and tenant improvements
  features/commands/organization_commands.feature
  features/commands/tenant_commands.feature
  src/SWP/Behat/Contexts/CommandContext.php
  src/SWP/Bundle/CoreBundle/Command/CreateOrganizationCommand.php
  src/SWP/Bundle/CoreBundle/Consumer/ImageConversionConsumer.php
  src/SWP/Bundle/MultiTenancyBundle/Command/CreateOrganizationCommand.php
  src/SWP/Bundle/MultiTenancyBundle/Command/CreateTenantCommand.php
  src/SWP/Bundle/MultiTenancyBundle/Tests/Command/CreateOrganizationCommandTest.php
  src/SWP/Component/MultiTenancy/Model/OrganizationInterface.php
  src/SWP/Component/MultiTenancy/Model/TenantInterface.php
Labels: Improvement
